version: '3.7'
services:
  client_dev:
    container_name: client_dev
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client_dev
    tty: true
    ports:
      - 8080:8080
      - 6006:6006
    volumes:
      - ./client:/app/client
      - node_modules:/app/client/node_modules
    working_dir: /app/client

  server_dev:
    container_name: server_dev
    build:
      context: ./server
      dockerfile: Dockerfile
      target: server_dev
    tty: true
    ports:
      - 8888:8888
    volumes:
      - ./server:/app/server
    working_dir: /app/server

volumes:
  node_modules: {}
